// Official list of Donsol, Sorsogon's 51 barangays (PhilAtlas/PSA PSGC),
// alphabetical. Used to constrain the Barangay field to real Donsol
// barangays instead of free text, matching how GeoMapping (ProjectMap.jsx,
// utils/geo.js) already scopes everything else to this one municipality.
export const DONSOL_BARANGAYS = [
  'Alin',
  'Awai',
  'Banban',
  'Bandi',
  'Banuang Gurang',
  'Baras',
  'Bayawas',
  'Bororan (Barangay 1)',
  'Cabugao',
  'Central (Barangay 2)',
  'Cristo',
  'Dancalan',
  'De Vera',
  'Gimagaan',
  'Girawan',
  'Gogon',
  'Gura',
  'Juan Adre',
  'Lourdes',
  'Mabini',
  'Malapoc',
  'Malinao',
  'Market Site (Barangay 3)',
  'New Maguisa',
  'Ogod (Crossing)',
  'Old Maguisa',
  'Orange',
  'Pangpang',
  'Parina',
  'Pawala',
  'Pinamanaan',
  'Poso (Poblacion)',
  'Punta Waling-Waling (Poblacion)',
  'Rawis',
  'San Antonio',
  'San Isidro',
  'San Jose',
  'San Rafael',
  'San Ramon',
  'San Vicente',
  'Santa Cruz',
  'Sevilla',
  'Sibago',
  'Suguian',
  'Tagbac',
  'Tinanogan',
  'Tongdol',
  'Tres Marias',
  'Tuba',
  'Tupas',
  'Vinisitahan',
]
